name: "tft"
estimator:
  _target_: DeepModel.DeepModel.tft.estimator.TemporalFusionTransformerEstimator
  batch_size: 64
optuna:
  num_heads:
    - categorical
    - [2,4,8]
  hidden_dim:
    - categorical
    - [16,32,64]
  lr:
    - float
    - [1e-5, 1e-2]
    - log: True